server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone:http://localhost:8061/eureka/


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled:true

      routes:
      - id: gateway_service
        #uri: lb://gateway_service
        uri: http://localhost:8081
        predicates:
        - Path=/athlete-service/api/createTrainingSession
        filters:
          StripPrefix=1

